### Sign up a new user with an invitation code
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "anna@example.com",
  "password": "Sicher123!",
  "firstName": "Anna",
  "lastName": "Mustermann",
  "invitationCode": "M6NR"
}