### Signup – Token holen (einmalig oder mit neuer E-Mail)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Mustermann",
  "email": "anna.mustermann@gmx.de",
  "password": "Secret123!",
  "invitationCode": "ZZX-BNR"
}
