<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>ecfce4c2-6421-4fd6-8ce6-b686427de58d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KulturHub.Application\KulturHub.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.72" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
      <PackageReference Include="Npgsql" Version="10.0.2" />
      <PackageReference Include="Supabase" Version="1.1.1" />
    </ItemGroup>

</Project>
