<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>6e624591-7875-4f6e-bc3c-95870bfbcfa3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\KulturHub.Application\KulturHub.Application.csproj" />
        <ProjectReference Include="..\KulturHub.Infrastructure\KulturHub.Infrastructure.csproj" />
        <ProjectReference Include="..\KulturHub.Domain\KulturHub.Domain.csproj" />
    </ItemGroup>

</Project>
