### Invite a user to an organisation by email (requires valid JWT in @token)
@organisationId = 1a13fc95-c652-49fa-8773-cd41941f3bda

POST {{baseUrl}}/organisations/{{organisationId}}/memberships/invites
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "anna.mustermann@gmx.de"
}
