### List memberships of an organisation (requires valid JWT in @token)
@organisationId = 1a13fc95-c652-49fa-8773-cd41941f3bda

GET {{baseUrl}}/organisations/{{organisationId}}/memberships
Authorization: Bearer {{token}}
