### List Invitations (open only – default)
GET {{baseUrl}}/invitations
Authorization: Bearer {{token}}

### List Invitations (open + used)
GET {{baseUrl}}/invitations?includeUsed=true
Authorization: Bearer {{token}}

### List Invitations (open + expired)
GET {{baseUrl}}/invitations?includeExpired=true
Authorization: Bearer {{token}}

### List Invitations (all)
GET {{baseUrl}}/invitations?includeUsed=true&includeExpired=true
Authorization: Bearer {{token}}
