<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>cb6ba10c-8ded-4dce-b4fc-97a7d26d218b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KulturHub.Infrastructure\KulturHub.Infrastructure.csproj" />
        <ProjectReference Include="..\KulturHub.Domain\KulturHub.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.0.1" />
      <PackageReference Include="FluentValidation" Version="11.11.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Ports\" />
    </ItemGroup>

</Project>
